raspberry:
  - hosts:
    - "192.168.1.1"
    - "192.168.1.1"
    user: login
    pass: pass
  - hosts:
    - "192.168.1.1"
    user: login
    pass: pass
server:
  - hosts:
    - "192.168.1.1"
    user: login
    pass: pass